In [1]:
import numpy as np

## Creating Arrays


In [2]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

## Array Operations


In [4]:
print(f"array + 10 = {array + 10}")
print(f"array * 2 = {array * 2}")
print(f"array ^ 2 = {array ** 2}")

array + 10 = [11 12 13 14 15]
array * 2 = [ 2  4  6  8 10]
array ^ 2 = [ 1  4  9 16 25]


## Reshaping Arrays


In [49]:
array = np.arange(1, 10)

reshaped_array = array.reshape(3, 3)

reshaped_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
array = np.arange(1, 10)
print(array.flatten())

[1 2 3 4 5 6 7 8 9]


## Sum, Mean, and Standard Deviation


In [50]:
array = np.arange(1, 6)

print(f"array = {array}")

print(f"sum = {np.sum(array)}")
print(f"mean = {np.mean(array)}")
print(f"Standard Deviation = {np.std(array)}")


array = [1 2 3 4 5]
sum = 15
mean = 3.0
Standard Deviation = 1.4142135623730951


In [55]:
# Finding the sum of all the elements in an Array:
MyArray = np.arange(1, 13).reshape(3, 4)
print(MyArray)

print("\nThe sum of all the elements in the array MyArray is:",MyArray.sum())
print("\nThe sum of all the elements of each row of the array MyArray is:",MyArray.sum(axis=0))
print("\nThe sum of all the elements of each column of the array MyArray is:",MyArray.sum(axis=1))
print("\nThe sum of all the elements of the 3rd column of the array MyArray is:",MyArray[:,2].sum())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

The sum of all the elements in the array MyArray is: 78

The sum of all the elements of each row of the array MyArray is: [15 18 21 24]

The sum of all the elements of each column of the array MyArray is: [10 26 42]

The sum of all the elements of the 3rd column of the array MyArray is: 21


In [57]:
# Finding the minimum value of all the elements in an Array:
MyArray = np.array([[1,2,3,7],[5,-6,7,8],[9,10,11,12],[13,14,15,16]])
print(MyArray)

print("\nThe minimum value of all the elements in the array MyArray is:",MyArray.min())
print("\nThe minimum value of all the elements of each row of the array MyArray is:",MyArray.min(axis=0))
print("\nThe minimum value of all the elements of each column of the array MyArray is:",MyArray.min(axis=1))
print("\nThe minimum value of all the elements of the 2nd row of the array MyArray is:",MyArray[1,:].min())

[[ 1  2  3  7]
 [ 5 -6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

The minimum value of all the elements in the array MyArray is: -6

The minimum value of all the elements of each row of the array MyArray is: [ 1 -6  3  7]

The minimum value of all the elements of each column of the array MyArray is: [ 1 -6  9 13]

The minimum value of all the elements of the 2nd row of the array MyArray is: -6


## Create a 4x4 Identity Matrix

In [11]:
iden_mat = np.eye(4)
iden_mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Generate an Array of 5 Random Numbers Between 0 and 1

In [24]:
rand_arr = np.random.random(5)
rand_arr

array([0.9039542 , 0.9484113 , 0.69221572, 0.5362541 , 0.30094362])

random int number between 1 and 10 with shape (3, 3)

In [25]:
arr = np.random.randint(1, 11, (3, 3))
arr

array([[ 1,  1,  3],
       [ 3,  8, 10],
       [10,  4,  4]])

## Create a 3x3 Matrix with Values Ranging from 0 to 8

In [13]:
mat = np.arange(9).reshape(3, 3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
mat = np.arange(start = 2, stop = 11, step = 2)
mat

array([ 2,  4,  6,  8, 10])

## Create a Random Vector of Size 10 and Sort It

In [14]:
v = np.random.random(10)
sort_v = np.sort(v)

print(f"v = {v}")
print(f"sorted v = {sort_v}")

v = [0.24470133 0.72325069 0.73709933 0.42488594 0.62486928 0.5151607
 0.21155786 0.78968836 0.85384985 0.83089883]
sorted v = [0.21155786 0.24470133 0.42488594 0.5151607  0.62486928 0.72325069
 0.73709933 0.78968836 0.83089883 0.85384985]


## creates an array with a range of elements from start to stop with 'num' number of elements.


In [18]:
#Endpoint includes the last element or not

arr1 = np.linspace(start = 0, stop = 1, num = 5, endpoint = True)
print(arr1)

arr2 = np.linspace(start = 0, stop = 1, num = 5, endpoint = False)
print(arr2)

[0.   0.25 0.5  0.75 1.  ]
[0.  0.2 0.4 0.6 0.8]


## use copy

In [26]:
arr3 = arr2

arr3[0] = 3
arr2

array([3. , 0.2, 0.4, 0.6, 0.8])

In [29]:
A = np.random.randint(1, 51, (2, 2))

print(f"A= {A}\n")

B = A.copy()

B[0,0] = 100
print(f"B = {B}\n")
print(f"A after copy {A}")

A= [[22 35]
 [25 41]]

B = [[100  35]
 [ 25  41]]

A after copy [[22 35]
 [25 41]]


<h2>Adding elements<h2>

To add elements to a NumPy Array, we can use:
* np.append()
* np.insert()
* np.concatenate()

In [31]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### np.append() flattens the array and adds the new elements at the end of the array

In [32]:
arr2 = np.append(arr, [9, 10, 11])
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### np.insert()
#### flattens the array and adds the new elements before the idx index here

 #### or change axis from none to 0 or 1

In [33]:
idx = 2
arr3 = np.insert(arr, idx, [9, 10, 11])
arr3

array([ 0,  1,  9, 10, 11,  2,  3,  4,  5,  6,  7,  8])

In [34]:
arr4 = np.insert(arr, idx, [9, 10, 11], axis = 0)
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 9, 10, 11],
       [ 6,  7,  8]])

In [35]:
arr5 = np.insert(arr, idx, [9, 10, 11], axis = 1)
arr5

array([[ 0,  1,  9,  2],
       [ 3,  4, 10,  5],
       [ 6,  7, 11,  8]])

### np.concatenate() concatenates 2 NumPy arrays together

In [36]:
x = np.array([[1,2],
              [3,4]])

y = np.array([[5,6],
              [7,8]])


In [37]:

z = np.concatenate((x, y), axis = 0) # default = 0
z

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [38]:

w = np.concatenate((x, y), axis = 1)
w

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### We can also use np.hstack() and np.vstack()

In [39]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

z = np.vstack((x,y))
print(z)

z = np.hstack((x,y))
print(z)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]





<h2>Deleting Elements<h2>

We use np.delete()\
np.delete() flattens the array first and then deletes the element at the idx index here!\

to delete row make axis = 0
to delet column make axis = 1

In [40]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) # [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(a)
idx = 2
b = np.delete(a,idx)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 4 5 6 7 8 9]


In [42]:
a_del_row = np.delete(a,2,axis=0)
print(a_del_row)

[[1 2 3]
 [4 5 6]]


In [43]:
a_del_col = np.delete(a,2,axis=1)
print(a_del_col)

[[1 2]
 [4 5]
 [7 8]]


<h2>Accessing Array Attributes<h2>

There are 3 main Array Attributes that are important to know and will be useful:
* ndarray.ndim
* ndarray.size
* ndarray.shape

In [44]:
MyArray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(MyArray)

print("The number of dimensions of my array is:",MyArray.ndim)
print("The size (the total amount of elements) of my array is:",MyArray.size)
print("The shape of my array is:",MyArray.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The number of dimensions of my array is: 2
The size (the total amount of elements) of my array is: 9
The shape of my array is: (3, 3)


# <h2>Transposing an array<h2>

You can transpose an array with nparray.transpose() and nparray.T


In [52]:
# Transposing an Array:
MyArray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(MyArray)

print("\nThe tranpose of MyArray is:\n",MyArray.transpose())

print("\nThe tranpose of MyArray can be done with MyArray.T and gives us:\n",MyArray.T)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

The tranpose of MyArray is:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

The tranpose of MyArray can be done with MyArray.T and gives us:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


<h2>See all the unique values in an array and their counts using np.unique()<h2>

In [58]:
arr =  np.array([1,1,1,2,2,3,3,3,3,4,5,5,5])

unq = np.unique(arr)
unq

array([1, 2, 3, 4, 5])

In [59]:
unq, cnt = np.unique(arr, return_counts = True)
print(cnt)

[3 2 4 1 3]


<h2>Conditional Selection<h2>

Finding the elements that meet certain condition(s).

To do this, you:
1.   generate a mask from your conditions
2.   use the mask to index the values that meet the condition

Let's take a look at how to do it:

In [60]:
#Find all the even numbered elements in the array that is greater than 6:

MyArray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(MyArray)

# First, we generate our mask that meets our conditions (condition 1: even, condition 2: > 6):
mask = (MyArray%2==0) & (MyArray > 6)
print(mask)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[False False False False]
 [False False False  True]
 [False  True False  True]
 [False  True False  True]]


In [61]:
# Second, we use this mask as an index to get the values that meet our conditions:
selected = MyArray[mask]
print(selected)

[ 8 10 12 14 16]
